import { CreateSalesInvoiceInput, CreateSalesInvoiceItemInput } from '@vyora/types';

export interface UiLineItem {
  productId?: string | null;
  productName?: string;
  qty?: number | string;
  rate?: number | string;
  discountPercent?: number | string;
  taxPercent?: number | string;
  amount?: number | string;
}

export interface UiSalesInvoiceState {
  customer?: string;
  customerGstin?: string;
  customerAddress?: string;
  billingName?: string;
  billingGstin?: string;
  billingAddress?: string;
  billingCity?: string;
  billingStateCode?: string;
  billingStateName?: string;
  billingPincode?: string;
  shippingSameAsBilling?: boolean;
  shippingName?: string;
  shippingGstin?: string;
  shippingAddress?: string;
  shippingCity?: string;
  shippingStateCode?: string;
  shippingStateName?: string;
  shippingPincode?: string;
  placeOfSupplyCode?: string;
  invoiceDate?: Date | string;
  referenceNumber?: string;
  lines?: UiLineItem[];
}

export function mapSalesInvoiceUiToDto(
  uiState: UiSalesInvoiceState,
  companyId: string,
  financialYearId: string,
  calculationResult: import('@vyora/types').InvoiceCalculationResult,
  engineInput: import('@vyora/types').CalculationEngineInput,
): CreateSalesInvoiceInput {
  const items: CreateSalesInvoiceItemInput[] = (uiState.lines || [])
    .filter((line: UiLineItem) => line.productId && Number(line.qty) > 0)
    .map((line: UiLineItem, index: number) => {
      const engineLine = calculationResult.items[index];
      const inputLine = engineInput.items[index];

      return {
        productId: line.productId || '',
        // Using placeholders for unitId/taxId until future phases implement proper unit/tax selectors
        unitId: '11111111-1111-4111-8111-111111111111',
        taxId: '22222222-2222-4222-8222-222222222222',
        description: line.productName,
        hsnCode: '',
        quantity: inputLine ? inputLine.quantity : Number(line.qty) || 0,
        rate: inputLine ? inputLine.rate : 0,
        discountAmount: inputLine ? inputLine.discountAmount : 0,
        taxableAmount: engineLine ? engineLine.taxableAmount : 0,
        taxAmount: engineLine ? engineLine.taxAmount : 0,
        lineTotal: engineLine ? engineLine.lineTotal : 0,
      };
    });

  return {
    companyId,
    financialYearId,
    customerId: uiState.customer || '',
    invoiceNumber: 'DRAFT', // Usually generated by backend
    invoiceDate: uiState.invoiceDate ? new Date(uiState.invoiceDate) : new Date(),
    isReverseCharge: false,
    subtotal: calculationResult.subtotal,
    discountAmount: calculationResult.totalDiscount,
    taxAmount: calculationResult.totalTax,
    roundOffAmount: calculationResult.roundOffAmount,
    grandTotal: calculationResult.grandTotal,
    notes: uiState.referenceNumber || null,
    status: 'DRAFT',
    items,
  };
}
