import { CreateSalesInvoiceInput, CreateSalesInvoiceItemInput } from '@vyora/types';

export interface UiLineItem {
  productId?: string | null;
  productName?: string;
  qty?: number | string;
  rate?: number | string;
  discountPercent?: number | string;
  taxPercent?: number | string;
  amount?: number | string;
}

export interface UiSalesInvoiceState {
  customer?: string;
  customerGstin?: string;
  customerAddress?: string;
  billingName?: string;
  billingGstin?: string;
  billingAddress?: string;
  billingCity?: string;
  billingStateCode?: string;
  billingStateName?: string;
  billingPincode?: string;
  shippingSameAsBilling?: boolean;
  shippingName?: string;
  shippingGstin?: string;
  shippingAddress?: string;
  shippingCity?: string;
  shippingStateCode?: string;
  shippingStateName?: string;
  shippingPincode?: string;
  placeOfSupplyCode?: string;
  invoiceDate?: Date | string;
  referenceNumber?: string;
  lines?: UiLineItem[];
}

export function mapSalesInvoiceUiToDto(
  uiState: UiSalesInvoiceState,
  companyId: string,
  financialYearId: string,
): CreateSalesInvoiceInput {
  let subtotal = 0;
  let discountTotal = 0;
  let taxableAmount = 0;
  let taxTotal = 0;

  const items: CreateSalesInvoiceItemInput[] = (uiState.lines || [])
    .filter((line: UiLineItem) => line.productId && Number(line.qty) > 0)
    .map((line: UiLineItem) => {
      const qty = Number(line.qty) || 0;
      const rate = Number(line.rate) || 0;
      const discPct = Number(line.discountPercent) || 0;
      const taxPct = Number(line.taxPercent) || 0;

      const lineGross = qty * rate;
      const discountAmount = lineGross * (discPct / 100);
      const lineTaxableAmount = lineGross - discountAmount;
      const taxAmount = lineTaxableAmount * (taxPct / 100);
      const lineTotal = lineTaxableAmount + taxAmount;

      subtotal += lineGross;
      discountTotal += discountAmount;
      taxableAmount += lineTaxableAmount;
      taxTotal += taxAmount;

      return {
        productId: line.productId || '',
        // Using placeholders for unitId/taxId until future phases implement proper unit/tax selectors
        unitId: 'default_unit',
        taxId: 'default_tax',
        description: line.productName,
        hsnCode: '',
        quantity: qty,
        rate: rate,
        discountAmount: discountAmount,
        taxableAmount: lineTaxableAmount,
        taxAmount: taxAmount,
        lineTotal: lineTotal,
      };
    });

  const unroundedTotal = taxableAmount + taxTotal;
  const grandTotal = Math.round(unroundedTotal);
  const roundOff = grandTotal - unroundedTotal;

  return {
    companyId,
    financialYearId,
    customerId: uiState.customer || '',
    invoiceNumber: 'DRAFT', // Usually generated by backend
    invoiceDate: uiState.invoiceDate ? new Date(uiState.invoiceDate) : new Date(),
    subtotal: subtotal,
    discountAmount: discountTotal,
    taxAmount: taxTotal,
    roundOffAmount: roundOff,
    grandTotal: grandTotal,
    notes: uiState.referenceNumber || null,
    status: 'DRAFT',
    items,
  };
}
