ALTER TABLE `customers` ADD `district` text;--> statement-breakpoint
ALTER TABLE `suppliers` ADD `district` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `place_of_supply_code` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_name_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_address_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_gstin_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_state_name_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_state_code_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `company_pan_snapshot` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_name` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_address` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_city` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_district` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_pincode` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_gstin` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `billing_state_code` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_name` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_address` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_city` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_district` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_pincode` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_gstin` text;--> statement-breakpoint
ALTER TABLE `sales_invoices` ADD `shipping_state_code` text;