export * from './appSettingsHandlers';
export * from './bootstrapHandlers';
export * from './calculationHandlers';
export * from './companyHandlers';
export * from './countryHandlers';
export * from './currencyHandlers';
export * from './customerHandlers';
export * from './financialYearHandlers';
export * from './inventoryHandlers';
export * from './journalHandlers';
export * from './pincodeHandlers';
export * from './printHandlers';
export * from './productHandlers';
export * from './purchaseHandlers';
export * from './salesHandlers';
export * from './stateHandlers';
export * from './taxHandlers';
export * from './unitHandlers';
export * from './uqcHandlers';
export * from './hsnHandlers';
export * from './reportsHandlers';
export * from './sacHandlers';
export * from './accountingHandlers';
export * from './authHandlers';
export * from './systemHandlers';
export * from './documentNumberingHandlers';
export * from './paymentAccountHandlers';
export * from './fundTransferHandlers';
export * from './developerDatabaseHandlers';
export * from './expensePresetHandlers';
export * from './exportHandlers';
export * from './employeeTypeHandlers';
export * from './departmentHandlers';
export * from './designationHandlers';
export * from './workLocationHandlers';
export * from './employeeExpenseTypeHandlers';
export * from './leaveTypeHandlers';
export * from './holidayHandlers';
import { DeveloperFeatures } from '../../main/DeveloperFeatures';

import { registerAccountingHandlers } from './accountingHandlers';
import { registerAppSettingsHandlers } from './appSettingsHandlers';
import { registerAuthHandlers } from './authHandlers';
import { registerBootstrapHandlers } from './bootstrapHandlers';
import { registerCalculationHandlers } from './calculationHandlers';
import { registerChartOfAccountsHandlers } from './chartOfAccountsHandlers';
import { registerCompanyHandlers } from './companyHandlers';
import { registerCountryHandlers } from './countryHandlers';
import { registerCurrencyHandlers } from './currencyHandlers';
import { registerCustomerHandlers } from './customerHandlers';
import { registerDepartmentHandlers } from './departmentHandlers';
import { registerDesignationHandlers } from './designationHandlers';
import { registerDeveloperDatabaseHandlers } from './developerDatabaseHandlers';
import { registerDeveloperFeaturesHandlers } from './developerFeaturesHandlers';
import { registerDevHandlers } from './devHandlers';
import { registerDocumentNumberingHandlers } from './documentNumberingHandlers';
import { registerEmployeeBankDetailsHandlers } from './employeeBankDetailsHandlers';
import { registerEmployeeDocumentHandlers } from './employeeDocumentHandlers';
import { registerEmployeeExpenseTypeHandlers } from './employeeExpenseTypeHandlers';
import { registerEmployeeHandlers } from './employeeHandlers';
import { registerEmployeeTypeHandlers } from './employeeTypeHandlers';
import { registerExpensePresetHandlers } from './expensePresetHandlers';
import { registerExportHandlers } from './exportHandlers';
import { registerFinancialYearHandlers } from './financialYearHandlers';
import { registerFundTransferHandlers } from './fundTransferHandlers';
import { registerHolidayHandlers } from './holidayHandlers';
import { registerHsnHandlers } from './hsnHandlers';
import { registerInventoryHandlers } from './inventoryHandlers';
import { registerJournalHandlers } from './journalHandlers';
import { registerLeaveTypeHandlers } from './leaveTypeHandlers';
import { registerPaymentAccountHandlers } from './paymentAccountHandlers';
import { registerPincodeHandlers } from './pincodeHandlers';
import { registerPrintHandlers } from './printHandlers';
import { registerProductHandlers } from './productHandlers';
import { registerPurchaseHandlers } from './purchaseHandlers';
import { registerReportsHandlers } from './reportsHandlers';
import { registerSacHandlers } from './sacHandlers';
import { registerSalesInvoiceHandlers } from './salesHandlers';
import { registerStateHandlers } from './stateHandlers';
import { registerSupplierHandlers } from './supplierHandlers';
import { registerSystemHandlers } from './systemHandlers';
import { registerTaxHandlers } from './taxHandlers';
import { registerUnitHandlers } from './unitHandlers';
import { registerUqcHandlers } from './uqcHandlers';
import { registerWorkLocationHandlers } from './workLocationHandlers';

export function registerAllHandlers() {
  registerAuthHandlers();
  registerSystemHandlers();
  registerBootstrapHandlers();
  registerCalculationHandlers();
  registerCompanyHandlers();
  registerCustomerHandlers();
  registerFinancialYearHandlers();
  registerInventoryHandlers();
  registerJournalHandlers();
  registerProductHandlers();
  registerPurchaseHandlers();
  registerSupplierHandlers();
  registerSalesInvoiceHandlers();
  registerTaxHandlers();
  registerUnitHandlers();
  registerPrintHandlers();
  registerPincodeHandlers();
  registerCountryHandlers();
  registerCurrencyHandlers();
  registerStateHandlers();
  registerUqcHandlers();
  registerHsnHandlers();
  registerSacHandlers();
  registerAccountingHandlers();
  registerChartOfAccountsHandlers();
  registerReportsHandlers();
  registerDocumentNumberingHandlers();
  registerAppSettingsHandlers();

  registerPaymentAccountHandlers();
  registerFundTransferHandlers();
  registerExportHandlers();
  registerExpensePresetHandlers();
  registerEmployeeTypeHandlers();
  registerDepartmentHandlers();
  registerDesignationHandlers();
  registerWorkLocationHandlers();
  registerEmployeeExpenseTypeHandlers();
  registerEmployeeHandlers();
  registerEmployeeBankDetailsHandlers();
  registerEmployeeDocumentHandlers();
  registerLeaveTypeHandlers();
  registerHolidayHandlers();

  // Register unconditional developer features check
  registerDeveloperFeaturesHandlers();

  if (DeveloperFeatures.isEnabled()) {
    registerDevHandlers();
    registerDeveloperDatabaseHandlers();
  }
}
