export * from './bootstrapHandlers';
export * from './companyHandlers';
export * from './countryHandlers';
export * from './currencyHandlers';
export * from './customerHandlers';
export * from './financialYearHandlers';
export * from './inventoryHandlers';
export * from './pincodeHandlers';
export * from './printHandlers';
export * from './productHandlers';
export * from './purchaseHandlers';
export * from './salesHandlers';
export * from './stateHandlers';
export * from './taxHandlers';
export * from './uqcHandlers';
export * from './hsnHandlers';
export * from './sacHandlers';

import { registerBootstrapHandlers } from './bootstrapHandlers';
import { registerCompanyHandlers } from './companyHandlers';
import { registerCountryHandlers } from './countryHandlers';
import { registerCurrencyHandlers } from './currencyHandlers';
import { registerCustomerHandlers } from './customerHandlers';
import { registerFinancialYearHandlers } from './financialYearHandlers';
import { registerHsnHandlers } from './hsnHandlers';
import { registerInventoryHandlers } from './inventoryHandlers';
import { registerPincodeHandlers } from './pincodeHandlers';
import { registerPrintHandlers } from './printHandlers';
import { registerProductHandlers } from './productHandlers';
import { registerPurchaseHandlers } from './purchaseHandlers';
import { registerSacHandlers } from './sacHandlers';
import { registerSalesInvoiceHandlers } from './salesHandlers';
import { registerStateHandlers } from './stateHandlers';
import { registerTaxHandlers } from './taxHandlers';
import { registerUqcHandlers } from './uqcHandlers';

export function registerAllHandlers() {
  registerBootstrapHandlers();
  registerCompanyHandlers();
  registerCustomerHandlers();
  registerFinancialYearHandlers();
  registerInventoryHandlers();
  registerProductHandlers();
  registerPurchaseHandlers();
  registerSalesInvoiceHandlers();
  registerTaxHandlers();
  registerPrintHandlers();
  registerPincodeHandlers();
  registerCountryHandlers();
  registerCurrencyHandlers();
  registerStateHandlers();
  registerUqcHandlers();
  registerHsnHandlers();
  registerSacHandlers();
}
